### ISSUE TITLE
[Error] Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by mutr** [ros/solidworks_urdf_exporter#65]
`There was a problem with the configuration property manager:  "Object reference not set to an instance of an object."`

Plugin version: 1.5 (from wiki).
Solidworks version checked: 
2019 SP3.0 Premium
2016 SP3.0 Premium
Both have the same issue.

[sw2urdf.log](https://github.com/ros/solidworks_urdf_exporter/files/3215674/sw2urdf.log)

**Comment by mutr** [comment]
![2019-05-24_15-50-16](https://user-images.githubusercontent.com/4329026/58328779-a8b33d80-7e3b-11e9-872e-43f5ce69133c.png)

How to reproduce:
1. Download [urdf_test16.zip](http://www.mediafire.com/file/wdf2blu1qothe1h/urdf_test16.zip/file)
2. Open urdf_test.SLDASM
3. Select "Export as URDF"
4. Click "Preview and Export"

**Comment by brawner** [comment]
Thanks for the bug report. I can reproduce your issue. While the error message is very unhelpful and needs to be fixed for this case, the underlying issue is that bone_31 in your configuration doesn't have a part associated with it. Alternatively, if you'd like to leave that empty, change the joint type from "Detect automatically" to "fixed"
