### ISSUE TITLE
Quick question.

### ISSUE THREAD

**Issue by HenriqueHafner** [ros/solidworks_urdf_exporter#91]
Hi.
I would like to know in which script you call the SW API functions, I cannot find it.
Another point is, why not to use "mate" references" or native assembly data to generate the urdf links?

**Comment by brawner** [comment]
The use of the SW API is scattered throughout the code, the entry point when you click "Export to SW" in an assembly is [this method](https://github.com/ros/solidworks_urdf_exporter/blob/master/SW2URDF/SW/SwAddin.cs#L268). That opens up the [PropertyManager derived class](https://github.com/ros/solidworks_urdf_exporter/blob/master/SW2URDF/URDFExport/ExportPropertyManager.cs), where everything gets started, and you can follow the UI callbacks from there.

The mates _are_ used when you ask the assembly exporter to automatically detect the joint information. However, you still need to configure the setup of the robot into a URDF style link/joint tree. I haven't come up with a way to take an arbitrary solidworks model and build that tree automatically. Also, when using the automatic joint detection feature, the joints have to have one degree of freedom, otherwise there is no way to identify the joint type, origin or axis.
